---
image:
  name: starcraftman/cogtest:latest
  entrypoint: [""]

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - /etc/init.d/mariadb start
  - secrethub inject -i "tests/secrethub/secretConfig.yml" -o "data/config.yml"
  - secrethub inject -i "tests/secrethub/secretSheets.json" -o "data/service_sheets.json"

test:
  script:
    - ALL_TESTS=True python3 -m pytest --cov=cog --cov=cogdb
    - coveralls || true
pylint:
  script:
    - tox -e pylint
flake8:
  script:
    - tox -e flake8
---
