drop table if exists admins;
drop table if exists perms_role;
drop table if exists perms_channel;
drop table if exists um_merits;
drop table if exists merits;
drop table if exists um_systems;
drop table if exists systems;
drop table if exists sheet_users;
drop table if exists discord_users;
