name: Github CI
on: [push]

env:
  DB_DATABASE: test
  DB_USER: root
  DB_PASSWORD: root

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    # Example services for Mongodb, PostgreSQL and Redis can be found here:
    # https://github.com/actions/example-services/tree/master/.github/workflows
    steps:
    # Commands use passwordless sudo
    - uses: actions/checkout@v3
    - name: Install packages required for tests
      run: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates
        echo "deb [trusted=yes] https://apt.secrethub.io stable main" | sudo tee -a /etc/apt/sources.list.d/secrethub.sources.list
        sudo apt-get update && sudo apt-get install -y git build-essential python3-dev python3-pip libyajl2 jq secrethub-cli
    - name: Install pip dependencies
      run: python setup.py deps --force=yes
    - name: Setup database, tables and import EDDB dump.
      run: |
        sudo /etc/init.d/mysql start
        mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < "tests/mysql_tables.sql"
        curl "http://starcraftman.com/elite/eddb_v04.sql" > "eddb.sql"
        mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -D eddb < "eddb.sql"
    - name: Generate secret config files
      env:
        SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB }}
      run: |
        secrethub inject -i "tests/secrethub/secretConfig.yml" -o "data/config.yml"
        secrethub inject -i "tests/secrethub/secretSheets.json" -o "data/service_sheets.json"
    - name: Run unit tests
      # env:
        # ALL_TESTS: "True"
      # Running without full tests due to rate limiting of inara. See gitlab for full run.
      run: python -m pytest --cov=cog --cov=cogdb
